# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Reorder Payment Gateway"
client_id = "2e24cb94d13e0c38c3b5dc5ce3fd245b"
application_url = "https://ahead-shall-munich-homeland.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_payment_customizations,read_payment_customizations"

[auth]
redirect_urls = [
  "https://ahead-shall-munich-homeland.trycloudflare.com/auth/callback",
  "https://ahead-shall-munich-homeland.trycloudflare.com/auth/shopify/callback",
  "https://ahead-shall-munich-homeland.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
